name: 'App Pool Action'

description: 'This action can start, stop, or restart an IIS app pool that is hosted on an on-premises server'

inputs:
  action:
    description: Specify start, stop, restart as the action to perform
    default: 'start'
    required: true
  server:
    description: 'The name of the target server'
    required: true
  app-pool-name:
    description: 'IIS app pool name'
    required: true
  service-account-id:
    description: 'The service account name'
    required: true
  service-account-password:
    description: 'The service account password'
    required: true
    

runs:
  using: 'composite'
  steps:
    - name: Install PowerShell
      shell: bash
      run: |
        # Download and install PowerShell
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https software-properties-common
        wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell
        # Verify installation
        pwsh -v
    - uses: actions/checkout@v4
    - name: Install from PSGallery
      shell: pwsh
      run: |
        # Set-PSRepository PSGallery -InstallationPolicy Trusted
        # Install-Module -Name PSWSMan
        # Install-WSMan
        Install-WindowsFeature -name Web-Server -IncludeManagementTools
        Install-WindowsFeature Web-Asp-Net45
    - name: Action
      id: action
      shell: pwsh
      run: |
        $password_string = @'
        "${{ inputs.service-account-password }}"
        '@
        $secure_password = ConvertTo-SecureString -String $password_string -AsPlainText -Force
        ${{ github.action_path }}/iis_action.ps1 `
          -action "${{ inputs.action }}".ToLower() `
          -server ${{ inputs.server }} `
          -app_pool_name '${{ inputs.app-pool-name }}' `
          -user_id '${{ inputs.service-account-id }}' `
          -password $secure_password
