name: 'App Pool Action'

description: 'This action can start, stop, or restart an IIS app pool that is hosted on an on-premises server'

inputs:
  action:
    description: Specify start, stop, restart as the action to perform
    default: 'start'
    required: true
  server:
    description: 'The name of the target server'
    required: true
  app-pool-name:
    description: 'IIS app pool name'
    required: true
  service-account-id:
    description: 'The service account name'
    required: true
  service-account-password:
    description: 'The service account password'
    required: true
  server-public-key:
    description: 'Path to remote server public ssl key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Action
      id: action
      shell: powershell
      run: |
        $secure_password = ConvertTo-SecureString -String ${{ inputs.service-account-password }} -AsPlainText -Force
        ${{ github.action_path }}/iis_action.ps1 `
          -action "${{ inputs.action }}".ToLower() `
          -server ${{ inputs.server }} `
          -app_pool_name '${{ inputs.app-pool-name }}' `
          -user_id '${{ inputs.service-account-id }}' `
          -password $secure_password `
          -cert_path '${{ inputs.server-public-key }}'
